on: [workflow_dispatch]
name: Deploy to Azure Container Instance

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: docker.pkg.github.com
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t docker.pkg.github.com/rohitdemo/sharks-r-us/shark-facts-docker:latest .
            docker push docker.pkg.github.com/rohitdemo/sharks-r-us/shark-facts-docker:latest
        
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: shark-facts-rg
            dns-name-label: shark-demo
            image: docker.pkg.github.com/rohitdemo/sharks-r-us/shark-facts-docker:latest
            registry-login-server: docker.pkg.github.com
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: shark-container
            location: 'west us'
            ports: 80 8080
